# Generated by Django 4.0.3 on 2022-03-29 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', 'price', 'quantity'), 'verbose_name': 'Продукция', 'verbose_name_plural': 'Продукции'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
